version: "3"
services: 
  api_server:
    build:
      context: "./ndr_service/AI-Detector"
      dockerfile: "Dockerfile-ndr"
    ports:
      - "5000:5000"

  app:
    build: "./ndr_service/AI-Detector"
    ports:
      - "3000:5000"
    networks:
      - mynetwork

  schedule:
    build: 
      context: "./ndr_service/AI-Detector"
      dockerfile: "Dockerfile-schedule"
    ports:
      - "5555:5555"
    networks:
      - mynetwork

  es001:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.1
    restart: on-failure
    container_name: es001
    environment:
      - node.name=es001
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es002
      - cluster.initial_master_nodes=es001,es002
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms4g -Xmx4g"
      - cluster.routing.allocation.disk.threshold_enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./ndr_service/esdata/data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - mssp-net

  es002:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.1
    container_name: es002
    restart: on-failure
    environment:
      - node.name=es002
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es001
      - cluster.initial_master_nodes=es001,es002
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms4g -Xmx4g"
      - cluster.routing.allocation.disk.threshold_enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./ndr_service/esdata/data02:/usr/share/elasticsearch/data
    networks:
      - mssp-net

  PacketAnalyze:
    image: openjdk:11.0.8-jre
    container_name: cic
    restart: always
    network_mode: "host"
    tty: "true"
    mem_limit: "3G"
    volumes:
      - ./Packet_analyze/CICFlowMeter.jar:/CICFlowMeter.jar
      - ./Packet_analyze/libjnetpcap.so:/usr/local/openjdk-11/lib/libjnetpcap.so
      - ./Packet_analyze/libpcap.so.1.9.1:/usr/local/openjdk-11/lib/libpcap.so.0.8
      - ./Packet_analyze/log4g2.xml:/log4j2.xml
    environment:
      - "ES_IP=${ES_IP}"
      - "ES_PORT=${ES_PORT}"
      - "ES_INDEX_PREFIX=cic_"
      - "READ_LOCAL_FILE=FALSE"
      - "NETWORK_INTERFACE=${NETWORK_INTERFACE}"
      - "WRITE_TO_CSV=FALSE"
      - "BULK_WRITE_LEN=5"
    command: "java -Dlog4j.configurationFile=/log4j2.xml -jar /CICFlowMeter.jar -Xmx3g"

volumes:
  data01:
    driver: local
  data02:
    driver: local

networks:
  mssp-net:
    driver: bridge
  mynetwork:
    name: mynetwork

    
