version: "3.8"

services:
  backend: #服務名稱1，自定義
    build:
      context: "./upload_fastapi"
    container_name: md_api
    ports: #端口映對(
      - "9453:9453"
    volumes: #路徑映對(-v)
      - ./upload_fastapi:/app
      - .predict_images:/app/file2_images #local:docker
    networks: #網路環境
      - upload_sys
  frontend: #服務名稱2，自定義
    build: 
      context: ./startbootstrap-grayscale #目錄/路徑
    container_name: md_web
    networks:
      - upload_sys
    ports:
      - "3000:3000"
    volumes:
      - ./startbootstrap-grayscale:/web
      - ./predict_images:/web/dist/assets/img/result_img # 和backend的volume連動
  database:
    image: mongo
    container_name: mongoDB
    environment:
      #MONGO_INITDB_DATABASE: Files
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ransomtotal
    ports: 
      - "27017:27017"
    networks: #網路環境
      - upload_sys

networks:
  upload_sys:
    driver: bridge